project:
  type: book
  output-dir: docs
#include-in-header: custom-head.html

book:
  title: "Competing in the Age of AI"
  author: "Pamela Schlosser"
  date: "10/13/2025"
  chapters:
    - index.qmd

    - part: "AI in Business"
      chapters:
        - rethinkingfirm.qmd
        - genAI.qmd
        - ethics.qmd
        - analyticsproblem.qmd
        - preparingpeople.qmd
        - storytelling.qmd

    - part: "Python & Analytics Tools"
      chapters:
        - crashcourse.qmd
        - dataAcquisition.qmd
        - webscrapingandapi.qmd
        - introdash.qmd
        - makingcallbacks.qmd
        - multilayout.qmd
        - multipages.qmd
        - github.qmd

    - summary.qmd
    - references.qmd


format:
  html:
    css: styles.css
    number-sections: false
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"

editor: visual
